[package]
name = "genome-consciousness-ai"
version = "0.1.0"
edition = "2021"
authors = ["Jack <jack@genomics.ai>"]
description = "AI-driven genome sequencing and analysis toolkit"
license = "MIT"
repository = "https://github.com/your-username/genome-consciousness-ai"

[dependencies]
# Core functionality
tokio = { version = "1.35", features = ["full"] }
async-trait = "0.1.74"
futures = "0.3"

# Error handling and logging
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

# Bioinformatics
bio = "1.3"
rust-htslib = "0.44"
needletail = "0.5"

# Machine Learning
tch = "0.13"      # PyTorch bindings for Rust
ndarray = "0.15"
smartcore = "0.3"

# CLI and configuration
clap = { version = "4.4", features = ["derive"] }
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Visualization and data processing
plotters = "0.3"
csv = "1.3"
rayon = "1.8"

[dev-dependencies]
criterion = "0.5"
mockall = "0.12"
test-case = "3.3"
proptest = "1.4"

[[bench]]
name = "sequence_analysis"
harness = false
